### ISSUE TITLE
Project still in progress?

### ISSUE THREAD

**Issue by pat2381** [BytexDigital/BytexDigital.Steam#10]
Hey
my first question: is this project still under development?

And is it possible to make this available for Net. Framework. That would be really nice.

best regards
Jim

**Comment by RyanTT** [comment]
Hello, 
the library is currently mostly developed if we have personal need for it, however the library still should work just fine as we use it in some projects.

What .NET Framework version are you looking for in terms of support? .NET Standard 2.0 would mean you'd need at least .NET Framework 4.6.1 to use this lib.

**Comment by pat2381** [comment]
Hello Ryan, 
thanks for your answer.
In my current project I am using .NET Framework 4.7.2 but I think I could switch to version 4.6.1. Assuming you can also switch to .NET Standard 2.0?
Or is there another way to make it compatible?

**Comment by RyanTT** [comment]
Hello,
if we downgraded the library to NET Standard 2.0, you could use it in any .NET Framework version >= 4.7.2. If I may ask though, what kind of app are you running on .NET Framework? Is it a Windows Forms / WPF application?

**Comment by pat2381** [comment]
Hello ryan,
that would be really great if you would do that.
I'm currently trying to make a ModDownloader for an Arma Clan and I'm using WinForms here. I have to admit that my programming experience is not that good, but I'm learning a lot right now. There is currently nothing that makes downloading workshop items as easy as you do.

**Comment by RyanTT** [comment]
Would it be possible for you to upgrade your WinForms project to .NET?

There is an [official upgrade path from .NET Framework to .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0).

I might still consider downgrading the requirement to NET Standard 2.0, but I'd prefer not to as it would require some changes and remove QoL changes that .NET Standard 2.0 does not have.

**Comment by pat2381** [comment]
Hey,

ok i understand that changing will be a big task.

So that you don't have to adapt your project, I decided to change my project. I don't know if this will work out yet, but I'll try.

I still have one more question?

I created a small test project and found out that the FileDownloaded event from the IDownlaodhandler only fires after the first file has been loaded! But if I want to display the status now, and the file is very large, then I don't get any information about the file that is currently being loaded until it has finished loading! Is there a way to get this information anyway?

What I also noticed is that the application needs about 60 Mb of RAM after starting, but when I load a workshop item that is around 1.5Gb in size, it requires more than 600-800 Mb of RAM, even if the Download is ready. It also looks as if we are not releasing the memory here? Is this correct? What could I do here to free up the memory again?

**Comment by RyanTT** [comment]
IDownloadHandler has some properties that you can use for overall progress, [see here](https://github.com/BytexDigital/BytexDigital.Steam/blob/33c3381130a366c4321f9f52cab5dccb100cc726/BytexDigital.Steam/ContentDelivery/Models/Downloading/IDownloadHandler.cs#L10)

**Comment by RyanTT** [comment]
I've released a [dev build](https://github.com/BytexDigital/BytexDigital.Steam/packages/888734) that I'm testing in application right now myself to see if it helped any with RAM usage. I added some safeguards to have resourcers properly disposed (hopefully). I'll whether it will help or not.

**Comment by RyanTT** [comment]
Feel free to reopen if necessary.
