### ISSUE TITLE
Question: Does it uses nearest Steam login server or a certain one?

### ISSUE THREAD

**Issue by GoldJohnKing** [BytexDigital/BytexDigital.Steam#12]
Hi, I'm a user in China Mainland and we all know there's difficulty for Chinese people connecting to oversea servers.
The good news is, Steam has servers in China Mainland, so we still can connect to Steam without a VPN or so.

There's a project [FASTER](https://github.com/Foxlider/FASTER) using your [SteamCLI](https://github.com/BytexDigital/SteamCLI/tree/master/SteamCLI) library.
When I click "Download", it first needs to login to Steam, and it stucks here. However, with a VPN, it's able to login.

I can always login Steam via SteamCMD even without an VPN, so I wonder if your library uses a certain steam server to login?
If so, could you please make it possible to use nearest Steam login server?

Thanks.

**Comment by RyanTT** [comment]
Hello,

I can't make any promises, but I'll look into whether the library can support this.

In theory, it should already use the closest/by Steam proposed Servers, but China most likely requires special handling.

**Comment by RyanTT** [comment]
I'm afraid without access to a chinese account myself, I find it hard to debug this issue.

I have an idea on how this could end up working, but I have no way of testing these changes myself.

**Comment by RyanTT** [comment]
My assumption is that the current implementation fetches an incorrect list of CM servers, hence the internal Steam client is unable to connect because of chinese firewall restrictions.

However, when I use a chinese `cell_id` and `steamrealm=steamchina`, like in the following examples, I assume I am getting the correct list of servers?

https://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=148&format=vdf&launcher=7&steamrealm=steamchina

https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=148&max_servers=20

**Comment by RyanTT** [comment]
I've hardcoded this test client with a (presumably) chinese cell_id and to use the chinese Steam servers. Could you check whether you are able to sign in with it? It will attempt to download CUP Weapons.

You can start it the following way from Powershell:

```ps1
.\BytexDigital.Steam.TestClient.exe "USERNAME" "PASSWORD"
```

http://aki.cx/ce5ae0e1d1.zip

**Comment by GoldJohnKing** [comment]
Really sorry for replying soooo late, being really busy these months...

> My assumption is that the current implementation fetches an incorrect list of CM servers, hence the internal Steam client is unable to connect because of chinese firewall restrictions.
> 
> However, when I use a chinese `cell_id` and `steamrealm=steamchina`, like in the following examples, I assume I am getting the correct list of servers?
> 
> https://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=148&format=vdf&launcher=7&steamrealm=steamchina
> 
> https://api.steampowered.com/IContentServerDirectoryService/GetServersForSteamPipe/v1/?cell_id=148&max_servers=20

Yes, these seems the correct server list.


> I've hardcoded this test client with a (presumably) chinese cell_id and to use the chinese Steam servers. Could you check whether you are able to sign in with it? It will attempt to download CUP Weapons.
> 
> You can start it the following way from Powershell:
> 
> ```powershell
> .\BytexDigital.Steam.TestClient.exe "USERNAME" "PASSWORD"
> ```
> 
> http://aki.cx/ce5ae0e1d1.zip

However, I am unable to login with the exe above, it does not connect.

![image](https://user-images.githubusercontent.com/26923626/180585592-e375759c-20f5-44ff-8b03-d28a4e22c05f.png)

**Comment by GoldJohnKing** [comment]
> I'm afraid without access to a chinese account myself, I find it hard to debug this issue.
> 
> I have an idea on how this could end up working, but I have no way of testing these changes myself.

I guess there's no difference between Chinese and Global account, the major difference should be where we login Steam.

**Comment by RyanTT** [comment]
I updated the test clients code in the development branch to connect to a specific chinese server that's apparently in Shanghai, but for me it just results in a disconnect loop too.

I believe, unfortunately, that the library I use cannot handle SteamChina yet (apart from specifying which Steam server to use, I don't see any way of switching into a "SteamChina" mode), or more likely, I just don't understand SteamChina enough 😅

**Comment by GoldJohnKing** [comment]
> I updated the test clients code in the development branch to connect to a specific chinese server that's apparently in Shanghai, but for me it just results in a disconnect loop too.
> 
> I believe, unfortunately, that the library I use cannot handle SteamChina yet (apart from specifying which Steam server to use, I don't see any way of switching into a "SteamChina" mode), or more likely, I just don't understand SteamChina enough 😅

This link: https://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=148&format=vdf&launcher=7&steamrealm=steamchina

When we use `steamrealm=steamchina` or we do not specify the parameter, the URL returns with no `serverlist` items, only `serverlist_websockets`.
![image](https://user-images.githubusercontent.com/26923626/180627189-249c60cd-77f6-4a58-bc7c-e2b37a8d12f5.png)

While we use `steamrealm=steamglobal`, then it returns with both `serverlist` and `serverlist_websockets`.
![image](https://user-images.githubusercontent.com/26923626/180627201-3d8bb69f-8af9-4e94-943e-44711afda9ed.png)

I guess this might be the issue? Does the library you use handle only `serverlist` but not `serverlist_websockets`?

Another reason could be that Steam China is used only for our internal censored Steam platform, it can not be used to login global account, we should always force `steamrealm=steamglobal`.

**Comment by RyanTT** [comment]
The code in dev branch for the test client uses one specific server via the WebSocket protocol located in China, however a connection is not possible. The server list is correctly fetched and processed, but no connection to any of those servers in China is possible as far as I can tell

**Comment by GoldJohnKing** [comment]
> The code in dev branch for the test client uses one specific server via the WebSocket protocol located in China, however a connection is not possible. The server list is correctly fetched and processed, but no connection to any of those servers in China is possible as far as I can tell

That's really, really strange... 😖 

Then I guess I can only use a proxy for it... 😭 Thanks a lot for your efforts!
