### ISSUE TITLE
FileStream not getting closed

### ISSUE THREAD

**Issue by DragonGER** [BytexDigital/BytexDigital.Steam#2]
If downloading a workshop mod containing subdirectories including empty files in them the application will keep it in write mode open upon application closing.
This results in beeing unable to move the downloaded directory anywhere.

I guess there is an error in a filestream and it is not getting closed and disposed.

Visualisation:

@addon 
- addons 
  -- mypbo.pbo
- userconfig
   -- empty.sqf --> this file will kept open even after steamclient has been closed

Example workshop mod provided: https://steamcommunity.com/sharedfiles/filedetails/?id=2242952694
I noticed this while downloading the CBA Mod that includes a empty setting file in the userconfig folder

**Comment by RyanTT** [comment]
Fixed with #3
