### ISSUE TITLE
IDownloadHandler does not provide DownloadChangesToFolderAsync method

### ISSUE THREAD

**Issue by 3Mydlo3** [BytexDigital/BytexDigital.Steam#5]
This method is unavailable unless `MultipleFilesHandler` is created manually.

Native support in `SteamContentClient`/`IDownloadHandler` for items updating (and updates checking) would be nice.

**Comment by RyanTT** [comment]
Hello,

DirectFileHandler (as far as I can see) cannot support diff checking as no information about the content of the file is provided prior to downloading it (no chunks, no checksums).

Have you considered using an approach as follows?

```csharp
var downloadHandler = await steamContentClient.GetPublishedFileDataAsync(2242952694);

Task downloadTask = null;

if (downloadHandler is MultipleFilesHandler multipleFilesHandler)
{
    // Download with supported diff checking
    downloadTask = multipleFilesHandler.DownloadChangesToFolderAsync(@".\download");
}
else
{
    // Download without diff checking
    downloadTask = downloadHandler.DownloadToFolderAsync(@".\download");
}
```

My argument against declaring this method in the `IDownloadHandler` interface is that not every implemented handler supports it, so it seems like a misleading promise to be able to always have this method available to call.

An alternative I'd suggest is an extension method on `IDownloadHandler`  that uses either `DownloadChangesToFolderAsync` or `DownloadToFolderAsync` depending on which one is supported and that explains it's behaviour inside it's XML doc.

**Comment by 3Mydlo3** [comment]
I didn't consider this approach, I think it's worth a shot for now.

Still it doesn't seem right to cast interface to it's implementation in the long term, especially from testing perspective. Maybe it could be redesigned so there are separate methods for getting download handlers for both cases.

On the other side I don't see usage for `DirectFileHandler`, I don't know any example where only one file would be downloaded. It would be easier to think about some solution if I were familiar with some use case. Especially whether we know in advance if we want just one file.

**Comment by RyanTT** [comment]
> On the other side I don't see usage for DirectFileHandler, I don't know any example where only one file would be downloaded. It would be easier to think about some solution if I were familiar with some use case. Especially whether we know in advance if we want just one file.

Some files on the Steam workshop are not uploaded as a multifile upload, but rather one single file that has a direct download link URL. Such items do not provide any chunk metadata or else, thus I think it would be hard to generalize these two very different item types into one downloading class, as one type of workshop item provides very detailed data about the files present, whereas this special use case has no information provided except the link to download it from, the file size and the file name.

> Still it doesn't seem right to cast interface to it's implementation in the long term, especially from testing perspective. Maybe it could be redesigned so there are separate methods for getting download handlers for both cases.

Personally I'd be against introducing an alternative method for download handlers that offer this functionality, as it would imply you to know the correct applicable download handler in advance, which just shifts the check from "do I use this method or the other" from after the handler creation to after.

An alternative to casting to the implementation would be to introduce a second interface, e.g. `IDifferenceAwareDownloadHandler` which holds the `DownloadChangesToFolderAsync`. This would keep the user independent from what the actual handler is.

**Comment by 3Mydlo3** [comment]
I think adding `DownloadChangesToFolderAsync` to `IDownloadHandler` would be prefferable. For single file without any metadata beside file size and its name it could just download the file as normally or if you want, file size and name could be checked for changes. This way not much has to be changed to provide update functionality for both multiple and single files download using one common interface. And you can always include in docstring how it behaves for single file download case.

Introduction of `IDifferenceAwareDownloadHandler` is not much different than alternative method for download handlers with update capabilities.

**Comment by RyanTT** [comment]
`DownloadToFolderAsync` now performs validation of existing files when possible, so no separate method is required anymore.

I consider the old behavior to be unnecessary, as the user can always wipe the files via the given file list themselves before calling the Download method to achieve the previous behaviour.
