### ISSUE TITLE
SteamClient.ConnectAsync() hangs when SteamCredentials are empty

### ISSUE THREAD

**Issue by 3Mydlo3** [BytexDigital/BytexDigital.Steam#6]
When either `username` or `password` is empty string, below code won't throw an exception and will hang forever:
```cs
var steamCredentials = new SteamCredentials("", "");
var steamClient = new SteamClient(steamCredentials);
Console.WriteLine("Attempting connection with no username or password:");
try
{
    await steamClient.ConnectAsync();
    Console.WriteLine("I'll never print!");
}
catch (Exception)
{
    Console.WriteLine("Me neither!");
}
```

However debug output shows that some exceptions were thrown:
```
Exception thrown: 'System.ArgumentException' in SteamKit2.dll
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
```
And it happened in `SteamClient.AttemptLogin()`: https://github.com/BytexDigital/BytexDigital.Steam/blob/v0.7.42-beta/BytexDigital.Steam/Core/SteamClient.cs#L182-L192

Probably `_clientFaultedEvent.Set();` should be called when exception is thrown here.

**Comment by RyanTT** [comment]
Addressed with https://github.com/BytexDigital/BytexDigital.Steam/commit/504bbc898a9b42c2d48a3aae92661f7bd3a41569
Empty username is now considered an anonymous login attempt
