### ISSUE TITLE
ConnectAsync not throwing if Steam unreachable

### ISSUE THREAD

**Issue by Foxlider** [BytexDigital/BytexDigital.Steam#9]
I had an issue where if Steam is unreachable my app would just die without any exception being catched. 
I tracked down the issue to this function. It would get in ConnectAsync and then close without going into the `catch`

```cs
try
            { await _steamClient.ConnectAsync(tokenSource.Token); }
            catch (Exception ex)
            {
                
                Parameters.Output += $"\nFailed! Error: {ex.Message}";
                _steamClient.Shutdown();

                if (ex.GetBaseException() is SteamLogonException logonEx && logonEx.Result == SteamKit2.EResult.InvalidPassword)
                {
                    Parameters.Output += "\nWarning: The logon may have failed due to expired sentry-data." 
                                       + $"\nIf you are sure that the provided username and password are correct, consider deleting the .bin and .key file for the user \"{_steamClient.Credentials.Username}\" in the sentries directory."
                                       + $"{AppDomain.CurrentDomain.BaseDirectory}\\sentries";
                }
                return false;
            }

```

**Comment by RyanTT** [comment]
It does sound like there's a StackOverflow happening, I'll investigate

**Comment by Foxlider** [comment]
Let me know if I can help

**Comment by RyanTT** [comment]
I've added some code to prevent stackoverflows in the logon/login code flow.
Please try this version of the lib here available here:

https://github.com/BytexDigital/BytexDigital.Steam/packages/888734?version=0.8.1-development.1638977720

To add our package registry, please do the following (only required once):
1. Create a personal access token with your desired permissions [here](https://github.com/settings/tokens)
2. Add our package registry on your pc with the command

```
dotnet nuget add source --username YOUR_GITHUB_USERNAME --password YOUR_TOKEN --store-password-in-clear-text --name github_bytexdigital"https://nuget.pkg.github.com/BytexDigital/index.json"
```

**Comment by RyanTT** [comment]
Did this fix your issue?

**Comment by Foxlider** [comment]
Not yet. Did not have time to test yet.

**Comment by Foxlider** [comment]
It's all good ! fixed with the dev version
